# Generated by Django 4.1.13 on 2025-03-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_application_parsed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parsed_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
